apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
spec:
  selector:
    matchLabels:
      disktype: ssd1 
  template:
    metadata:
      labels:
        disktype: ssd1
    spec:
      containers:
      - name: nginx 
        image: nginx
        volumeMounts:
        - name: varlog
          mountPath: /usr/share/nginx
      volumes:
      - name: varlog
        hostPath:
          path: /usr/
      nodeSelector:
        gpupresent: "true"
