apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: myempty-storage
      mountPath: /usr/share/nginx
  volumes:
  - name: myempty-storage
    emptyDir: {}
  nodeSelector:
    demoserver: "true"