apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  storageClassName: manual
  # storageClassName: custom
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
