apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  serviceName: "nginx"
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx
        volumeMounts:
          - name: pv-data
            mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: pv-data
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Mi